# Generated by Django 5.2.4 on 2025-12-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='canva_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
